### ISSUE TITLE
hurry up

### ISSUE THREAD

**Issue by FredGoo** [matz/streem#110]
plz

**Comment by tbodt** [comment]
Wanna help?

**Comment by jonathanmarvens** [comment]
LOL.

**Comment by christopherdumas** [comment]
Is there any way I can help? Although I have to admit, I'm not great with C, I have some bison, lex, Nd yacc experiance.

**Comment by tbodt** [comment]
@christopherdumas Look at the code, figure out how it works, figure out how to improve it, and send pull requests.

**Comment by shevegen** [comment]
Don't take matz away from ruby!

Also, this issue is not exactly useful FredGoo. ;)

**Comment by FredGoo** [comment]
@shevegen  lol
just for fun

**Comment by mattn** [comment]
see https://github.com/matz/streem/issues/113
