### ISSUE TITLE
Does streem have a schedule ?

### ISSUE THREAD

**Issue by himcc** [matz/streem#113]
Does streem have a schedule ?

**Comment by matz** [comment]
It's opensource, so it doesn't have any concrete schedule nor roadmap.

But my development is paced by magazine articles on Nikkei Linux Magazine (Japanese).
So I develop new features of Streem in the first half of a month (along with writing articles), and check-in and debug in the latter half of a month, usually.

**Comment by tbodt** [comment]
Good to know. I was wondering why each push had something like 37 commits. I normally push after every commit.
