### ISSUE TITLE
task_tid function

### ISSUE THREAD

**Issue by xueyumusic** [matz/streem#125]
task_tid function in core.c chooses strm_task's tid based on max queue size when s->tid < 0 and tid parameter < 0, but I feel it might need using min queue size.  
I want to write a test case to cover this function's execution path   but don't know how to write a parallel streem program now or it does not support parallel program now.

The code snippet is 30-48 line in core.c
 
    else {
      int n = 0;
      int max = 0;
      for (i=0; i<thread_max; i++) {
        int size = strm_queue_size(threads[i].queue);
        if (size == 0) break;
        if (size > max) {
          max = size;
          n = i;
        }
      }
      if (i == thread_max) {
        s->tid = n;
      }
      else {
        s->tid = i;
      }
    }

**Comment by matz** [comment]
task_tid() function has been removed.
