### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [matz/streem#132]
I would like to point out that identifiers like "[`_NODE_H_`](https://github.com/matz/streem/blob/8c12120b41fc2e26b24cd1a9dc334d7395cc9779/src/node.h#L1)" and "[`_STRM_H_`](https://github.com/matz/streem/blob/8ea4193ab66cb85022632abbb9f812fece4f7b96/src/strm.h#L1)" [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by matz** [comment]
probably I will rename them with `STRM_` prefix, e.g `STRM_NODE_H` etc.

**Comment by elfring** [comment]
Are there [any more update candidates](https://github.com/matz/streem/blob/b8fcc0398840ecf322e50d7f72bf5d7d52494c08/src/khash.h#L157 "Reconsider identifier selection?") left over?
