### ISSUE TITLE
Is chan() can be use?

### ISSUE THREAD

**Issue by JackDrogon** [matz/streem#146]
When I run examples/08chat.strm, a error happened.

``` sh
$: bin/streem examples/08chat.strm
examples/08chat.strm:2:failed to assign
```

Git commit: 81c6ad9
System: Mac OSX 10.11
Clang: clang-703.0.29

or

System: CentOS7
GCC: 4.8.5

**Comment by matz** [comment]
No, chan() is not yet implemented. Sorry.
