### ISSUE TITLE
Homebrew formula for Streem

### ISSUE THREAD

**Issue by yamamuteki** [matz/streem#157]
I made a Homebrew formula for Streem because there was nothing.
I will try pull request to homebrew's official repository after making more.

https://github.com/yamamuteki/homebrew-streem

PS. I want to use it when I read the following. Thanks for your great experience.
http://amzn.asia/4fpBwY2

**Comment by matz** [comment]
Thank you. Although streem is not stable enough for daily use.
Please close the issue once the PR is accepted.

**Comment by yamamuteki** [comment]
> We don't accept formulae until they have stable releases. Feel free to resubmit when that's available!
https://github.com/Homebrew/homebrew-core/pull/9765

I close this issue, because PR was not accepted.
Thanks.
