### ISSUE TITLE
I read your book, curious how you test if the grammar work first. ARiGaDo!

### ISSUE THREAD

**Issue by zzz6519003** [matz/streem#169]
parse.y is so much too read...

**Comment by matz** [comment]
First I wrote a syntax checker to test syntax for the new language. `parse.y` with very basic syntax description (no actions), with simple lexer works well as a syntax checker. Check out f0df31008693df5496c69c43ed587a1bed71938d to see the syntax checker for Streem.

**Comment by zzz6519003** [comment]
and what does lex.l do? XD

**Comment by matz** [comment]
`Lex.l` is a source for the lexical analyzer. The tool named `lex` (or `flex` the GNU version) generates the C implementation of the lexical analyzer.
