### ISSUE TITLE
Conditional write for function objects

### ISSUE THREAD

**Issue by halogenandtoast** [matz/streem#44]
This might be completely strange, but I feel like the fizzbuzz example could benefit from some kind of conditional write operator for function operators. The syntax would be something like:

```
cond_expr => expr
```

When cond_expr is true the function object will stream that value to the next receiver

For example:

```
seq(100) | {|x|            
  x % 15 == 0 => "FizzBuzz"
  x % 3 == 0 => "Fizz"
  x % 5 == 0 => "Buzz"
  true => x
} | STDOUT
```

**Comment by matz** [comment]
@nicolasmccurdy right. A function return value or a value given to `emit` will be passed to the connecting stream.
