### ISSUE TITLE
Another procedural language

### ISSUE THREAD

**Issue by alexchamberlain** [matz/streem#50]
I think the idea of a well written, open source, stream-based/flow-based/data-flow language is a fantastic one. My only concern about this idea is the initial example

```
seq(100) | {|x|
  if x % 15 == 0 {
    "FizzBuzz"
  }
  else if x % 3 == 0 {
    "Fizz"
  }
  else if x % 5 == 0 {
    "Buzz"
  }
  else {
    x
  }
} | STDOUT
```

 Do we need an procedural language? Please ignore the syntax, but what about something like this:

```
from fizzbuzz import fizzbuzz
seq(100) | fizzbuzz | STDOUT
```

where `fizzbuzz` is a module written in a _conventional_ imperative language, such as Python, Ruby or C++?

**Comment by calebwin** [comment]
@alexchamberlain I've begin working on something somewhat along the lines of what you seem to be taking about - github.com/calebwin/pipelines
Comments/criticism would be appreciated.

**Comment by matz** [comment]
I like the basic idea of `pipelines`. Thank you!

**Comment by calebwin** [comment]
Thank you @matz; I'm glad you like it!
