### ISSUE TITLE
libevent

### ISSUE THREAD

**Issue by tbodt** [matz/streem#74]
The current implementation of I/O uses the `epoll` system call, which only exists on Linux. I think it should use libevent, which is a library for I/O polling that can use epoll, poll, select, etc. depending on the operating system. It seems pretty complicated, but I think it would be worth it. What do you think?

**Comment by mattn** [comment]
I prefer libuv

**Comment by matz** [comment]
libuv is single threaded library, as far as I understand. So I built event loop by myself.
